---
- name: Install multiple packages
  hosts: Test_servers
  become: true
  become_user: root
  tasks:
   - name: Install needed packages
     yum: 
      name={{item}} 
      state=present
     loop:
      - git
      - docker
   - name: Start docker service
     service: 
       name=docker 
       state=started
       
