---
- name: Install multiple packages
  hosts: Test_servers
  become: true
  become_user: root
  tasks:
    - name: install tomcat
      yum: 
       name: tomcat 
       state: present
    - name: start tomcat
      service: 
        name: tomcat 
        state: started
    - name: Install needed packages
      yum: 
        name: "{{item}}"
        state: present
      loop:
        - git
        - docker
    - name: Start docker service
      service: 
         name: docker 
         state: started
    - name: clone the github for dockerfile
      git:
         repo: https://github.com/mathucode/sample-project.git 
         dest: /tmp/project1_repo 
    - name: Copy addressbook.war to Dockerfile directory
      copy:
        src: /var/lib/jenkins/workspace/Project1/addressbook.war
        dest: /tmp/project1_repo/addressbook.war
    - name: Build the docker file  
      command:
         cmd: docker build -t myproject:1 .
         chdir: /tmp/project1_repo
    - name: create container
      command: docker run -itd -P myproject:1
    
