---
- name: Install multiple packages
  hosts: Test_servers
  become: true
  become_user: root
  tasks:
    - name: install tomcat
      yum: name=tomcat state=present
    - name: start tomcat
      service: name=tomcat state=started
    - name: Install needed packages
      yum: 
       name={{item}} 
       state=present
      loop:
       - git
       - docker
    - name: Start docker service
      service: 
        name=docker 
        state=started
    - name: clone the github  
    
       
