---
- name: Install multiple packages
  hosts: Test_servers
  become: true
  become_user: root
  tasks:
    - name: install tomcat
      yum: 
       name: tomcat 
       state: present
    - name: start tomcat
      service: 
        name: tomcat 
        state: started
    - name: Install needed packages
      yum: 
        name: {{item}} 
        state: present
      loop:
        - git
        - docker
    - name: Start docker service
      service: 
         name: docker 
         state: started
    - name: clone the github for dockerfile
      git: repo:https://github.com/mathucode/sample-project.git 
           dest:/tmp/project1_repo    
      command: chdir=/tmp/project1_repo docker build -t myproject:1 .
    - name: create container
      command: docker run -itd -P myproject:1
    
